name: Zampto Auto Renew

on:
  schedule:
    # 每天北京时间早上 9 点和晚上 9 点各自动执行一次
    - cron: '0 1,13 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
    - name: 签出项目代码
      uses: actions/checkout@v4

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: 安装系统依赖 (Linux 虚拟显示与 Chrome 必备组件)
      run: |
        sudo apt-get update
        sudo apt-get install -y x11-utils libxss1 libappindicator1 libgtk-3-0 xvfb

    - name: 安装 Python 依赖库
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 初始化 SeleniumBase 运行环境 (自动下载匹配的 ChromeDriver)
      run: |
        seleniumbase install chromedriver

    - name: Setup Gost Proxy
      run: |
          # 👇👇👇 正在启动gost代理 👇👇👇                
          wget -q https://github.com/ginuerzh/gost/releases/download/v2.11.5/gost-linux-amd64-2.11.5.gz
          gunzip -f gost-linux-amd64-2.11.5.gz
          chmod +x gost-linux-amd64-2.11.5
          
          echo "🔗 启动 Gost 隧道: $SOCKS5_URL"
          ./gost-linux-amd64-2.11.5 -L=http://:1080 -F="${{ secrets.SOCKS5_URL }}" > gost.log 2>&1 &
          
          sleep 5
          echo "--- 🌐 连通性测试 ---"
          curl -I -x http://127.0.0.1:1080 https://www.google.com

    - name: 启动自动化续期核心脚本
      env:
        ZAMPTO_EMAIL: ${{ secrets.ZAMPTO_EMAIL }}
        ZAMPTO_PASSWORD: ${{ secrets.ZAMPTO_PASSWORD }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        ZAMPTO_COOKIES: ${{ secrets.ZAMPTO_COOKIES }}
        ZAMPTO_ACCOUNT: ${{ secrets.ZAMPTO_ACCOUNT }}
      run: |
        python renew.py
